### ISSUE TITLE
Kata 76 - Promise Creation - doesn't wrok in TDDbin

### ISSUE THREAD

**Issue by rr326** [tddbin/katas#35]
I couldn't get the kata to resolve. So I checked out the original checkin (which should pass).  Tests 2&3 don't work. 

But pasting it into Chrome debugger, it works properly (as it should).

Test
```
  describe('extending a `Promise`', function() {
    it('is possible', function() {
      class MyPromise extends Promise {}
      const promise = new MyPromise(resolve => resolve());
      
      promise
        .then(() => done())
        .catch(e => done(new Error('Expected to resolve, but failed with: ' + e)));
    });
    it('must call `super()` in the constructor if it wants to inherit/specialize the behavior', function() {
      // WARNING: this example doesn't fulfill the Liskov principle
      class ResolvingPromise extends Promise {
        constructor() {
          super(resolve => resolve());
        }
      }
      
      return new ResolvingPromise();
    });
  });
```
Returns

> extending a `Promise`
is possible ‣
TypeError: #<MyPromise> is not a promise
    at new MyPromise (eval at runSpecs (http://tddbin.com/mocha/spec-runner.js:95056:7), <anonymous>:28:81)
    at eval (eval at runSpecs (http://tddbin.com/mocha/spec-runner.js:95056:7), <anonymous>:34:21)
    at r (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:9112)
    at r.o.run (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:9812)
    at o.runTest (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:13250)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:13824
    at r (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12787)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12763
    at n (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12554)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12618
must call `super()` in the constructor if it wants to inherit/specialize the behavior ‣
TypeError: #<ResolvingPromise> is not a promise
    at new ResolvingPromise (eval at runSpecs (http://tddbin.com/mocha/spec-runner.js:95056:7), <anonymous>:53:88)
    at eval (eval at runSpecs (http://tddbin.com/mocha/spec-runner.js:95056:7), <anonymous>:61:14)
    at r (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:9112)
    at r.o.run (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:9812)
    at o.runTest (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:13250)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:13824
    at r (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12787)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12763
    at n (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12554)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12618

In Chrome
```
done = (retval) => `done ${retval}`
(retval) => `done ${retval}`
      class MyPromise extends Promise {}
      const promise = new MyPromise(resolve => resolve());
      
      promise
        .then(() => done())
        .catch(e => done(new Error('Expected to resolve, but failed with: ' + e)));
```
Returns

> Promise  {[[PromiseStatus]]: "resolved", [[PromiseValue]]: "done undefined"}

**Comment by fourcolors** [comment]
Verified on my end.

**Comment by ragmha** [comment]
Same here

**Comment by Ibrahim-Islam** [comment]
For me it works on Chrome if Transpile to ES5 is turned off. Would like to know the reason though.

**Comment by sandbox992** [comment]
Have another problem:
` describe('extending a `Promise`', function() {
    it('using `class X extends Promise{}` is possible', function(done) {
      class MyPromise extends Promise {}
      const promise = new MyPromise(resolve => resolve());
      promise
        .then(() => done())
        .catch(e => done(new Error('Expected to resolve, but failed with: ' + e)));
    });
    it('must call `super()` in the constructor if it wants to inherit/specialize the behavior', function() {
      class ResolvingPromise extends Promise {
        constructor() {
          super()
        }
      }
      return new ResolvingPromise(resolve => resolve());
    });
  });`

Returns:
Method Promise.prototype.then called on incompatible receiver #<MyPromise>
Method Promise.prototype.then called on incompatible receiver #<ResolvingPromise>
for first and second tasks relatively

Similar problem(not mine, just found):
[(https://stackoverflow.com/questions/40404028/working-through-es6-katas-extending-promises)]

**Comment by wolframkriesing** [comment]
I was struggling to understand this issue. I played around with the kata, but I dont know what is meant that it doesnt work. If there is still interest, I would be keen on learning what the problem was (or still is).
