### ISSUE TITLE
Kata 28 - TDDbin add indentation to super.constructor

### ISSUE THREAD

**Issue by robosa** [tddbin/katas#53]
When calling super.constructor in last test you get

`AssertionError: 'class A {\n      constructor() {\n        "parent";\n      }\n\n    }' == 'class A {constructor() {"parent"}}'@spec-runner.js line 105073 > eval:77:5`

**Comment by jizusun** [comment]
I can reproduce the issue, 

* Chromium 69
* Without transpiling to ES5
```
❌use `super.constructor` to find out if there is a parent constructor ‣
AssertionError: 'class A {\n      constructor() {\n        "parent";\n      }\n\n    }' === 'class A {constructor() {"parent"}}'
    at n.it (eval at runSpecs (spec-runner.js:105073:7), <anonymous>:83:12)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.1.2/mocha.min.js:2:8479)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.1.2/mocha.min.js:2:9550)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.1.2/mocha.min.js:2:14329)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.1.2/mocha.min.js:2:14969
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.1.2/mocha.min.js:2:13794)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.1.2/mocha.min.js:2:13770
    at n (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.1.2/mocha.min.js:2:13561)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.1.2/mocha.min.js:2:13625
    at i (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.1.2/mocha.min.js:1:572)
```

After some tries and errors, I found the `class A` was pretty-printed when executing with mocha:
![image](https://user-images.githubusercontent.com/4011348/48000808-a7d9e900-e141-11e8-997c-e5afa9a57b4f.png)

But not when executing directly with Chrome or with Node.js

![image](https://user-images.githubusercontent.com/4011348/48000905-ec658480-e141-11e8-8f9d-367e2702cd8c.png)
